# Generated by Django 6.0.5 on 2026-05-23 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['user', 'done'], name='shopping_sh_user_id_930d7c_idx'),
        ),
    ]
