# Generated by Django 6.0.5 on 2026-05-23 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['user', 'month', 'day'], name='calendar_ap_user_id_32476e_idx'),
        ),
    ]
