# Generated by Django 6.0.5 on 2026-05-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_folder', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=16, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=120, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='files_app.filenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files_node',
                'ordering': ('-is_folder', 'name'),
                'indexes': [models.Index(fields=['user', 'parent'], name='files_node_user_id_66af39_idx')],
            },
        ),
    ]
