# Generated by Django 6.0.5 on 2026-05-23 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Video', max_length=300)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('downloading', 'Descargando'), ('ready', 'Listo'), ('error', 'Error')], default='downloading', max_length=16)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('torrent_source', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
