# Generated by Django 6.0.5 on 2026-05-23 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['user', 'status'], name='videos_vide_user_id_bff68c_idx'),
        ),
    ]
