# Generated by Django 6.0.5 on 2026-05-23 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['requester', 'status'], name='friends_fri_request_2ed2bb_idx'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['addressee', 'status'], name='friends_fri_address_fdc48f_idx'),
        ),
    ]
